import { useEffect, useState } from 'react'
import { aiSettingsApi, type AiSettings, type AiConfig, type SpeechProvider, type TextProvider, type ProcessingJob } from '@/lib/ai-settings'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Save, RefreshCw, X, Loader2 } from '@/components/icons'

const speech: SpeechProvider[] = ['whisper', 'mistral', 'deepgram', 'openai', 'assemblyai']
const text: TextProvider[] = ['mistral', 'openai', 'anthropic', 'ollama']
const labels: Record<string, string> = { whisper: 'Whisper.cpp', mistral: 'Mistral', deepgram: 'Deepgram', openai: 'OpenAI', assemblyai: 'AssemblyAI', anthropic: 'Anthropic', ollama: 'Ollama' }
const selectClass = 'h-10 w-full min-w-0 rounded-md border bg-background px-3 text-sm'
export function AiSettingsPanel() {
  const [settings, setSettings] = useState<AiSettings | null>(null)
  const [keys, setKeys] = useState<Record<string, string>>({})
  const [vocabulary, setVocabulary] = useState('')
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false)
  const [models, setModels] = useState<string[]>([]), [jobs, setJobs] = useState<ProcessingJob[]>([])
  useEffect(() => { let active = true; aiSettingsApi.get().then(value => { if (active) { setSettings(value); setVocabulary(value.transcriptionVocabulary.join(', ')) } }).catch(e => { if (active) setError(e.message) }); return () => { active = false } }, [])
  const update = (patch: Partial<AiConfig>) => { setNotice(''); if (patch.transcriptionVocabulary) setVocabulary(patch.transcriptionVocabulary.join(', ')); setSettings(value => value ? { ...value, ...patch } : value) }
  const action = async (run: () => Promise<void>) => { setBusy(true); setError(''); setNotice(''); try { await run() } catch (e) { setError(e instanceof Error ? e.message : 'AI settings unavailable.') } finally { setBusy(false) } }
  const save = () => action(async () => {
    if (!settings) return
    const config = Object.fromEntries(Object.entries(settings).filter(([key]) => !['credentials', 'capabilities'].includes(key))) as AiConfig
    config.transcriptionVocabulary = vocabulary.split(',').map(value => value.trim()).filter(Boolean)
    await aiSettingsApi.save(config, keys); setKeys({}); setSettings(await aiSettingsApi.get()); setNotice('AI settings saved')
  })
  if (!settings) return <section className="border-t pt-5" aria-label="AI providers">{error ? <p role="alert">{error}</p> : <p role="status">Loading AI settings...</p>}<Button variant="ghost" onClick={() => action(async () => setSettings(await aiSettingsApi.get()))}><RefreshCw />Retry</Button></section>
  const local = settings.privacyMode === 'local-only', capability = settings.capabilities[settings.transcriptionEngine]
  const used = [...new Set([settings.transcriptionEngine, ...settings.transcriptionFallback, settings.analysisProvider, settings.documentProvider, settings.chatProvider])].filter(provider => !['whisper', 'ollama'].includes(provider))
  return <section className="border-t pt-5 space-y-5" aria-label="AI providers">
    <div className="flex items-center justify-between gap-3"><h2 className="text-base font-semibold">AI providers</h2><Button disabled={busy} onClick={save}>{busy ? <Loader2 className="animate-spin" /> : <Save />}Save AI</Button></div>
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}{notice && <p role="status" className="text-sm">{notice}</p>}
    <label className="grid gap-2 text-sm">Processing privacy<select className={selectClass} disabled={busy} value={settings.privacyMode} onChange={e => update(e.target.value === 'local-only' ? { privacyMode: 'local-only', transcriptionEngine: 'whisper', transcriptionModel: '', transcriptionDiarize: false, transcriptionVocabulary: [], transcriptionFallback: [], analysisProvider: 'ollama', analysisModel: '', documentProvider: 'ollama', documentModel: '', chatProvider: 'ollama', chatModel: '' } : { privacyMode: 'selected-providers' })}><option value="selected-providers">Selected providers</option><option value="local-only">Local only</option></select></label>
    <fieldset disabled={busy} className="grid min-w-0 gap-4 sm:grid-cols-2"><legend className="mb-3 text-sm font-semibold">Transcription</legend>
      <label className="grid gap-2 text-sm">Provider<select className={selectClass} value={settings.transcriptionEngine} onChange={e => update({ transcriptionEngine: e.target.value as SpeechProvider, transcriptionModel: '', transcriptionDiarize: false, transcriptionVocabulary: [], transcriptionFallback: [] })}>{speech.map(provider => <option key={provider} disabled={local && provider !== 'whisper'} value={provider}>{labels[provider]}</option>)}</select></label>
      <label className="grid gap-2 text-sm">Model<select className={selectClass} value={settings.transcriptionModel} onChange={e => update({ transcriptionModel: e.target.value })}><option value="">{capability.models[0]} (default)</option>{capability.models.map(model => <option key={model}>{model}</option>)}</select></label>
      <label className="grid gap-2 text-sm">Language<select className={selectClass} value={settings.transcriptionLanguage} onChange={e => update({ transcriptionLanguage: e.target.value })}>{[['auto', 'Detect automatically'], ['en', 'English'], ['fr', 'French'], ['de', 'German'], ['es', 'Spanish'], ['it', 'Italian'], ['pt', 'Portuguese'], ['ja', 'Japanese'], ['zh', 'Chinese']].map(([code, label]) => <option key={code} value={code}>{label}</option>)}</select></label>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={!capability.diarization} checked={settings.transcriptionDiarize} onChange={e => update({ transcriptionDiarize: e.target.checked })} />Speaker labels</label>
      <label className="grid gap-2 text-sm sm:col-span-2">Vocabulary hints<Input disabled={!capability.vocabulary} value={vocabulary} onChange={e => { setVocabulary(e.target.value); setNotice('') }} /></label>
      <label className="grid gap-2 text-sm sm:col-span-2">Fallback provider<select className={selectClass} value={settings.transcriptionFallback[0] || ''} onChange={e => update({ transcriptionFallback: e.target.value ? [e.target.value as SpeechProvider] : [] })}><option value="">None</option>{speech.filter(provider => provider !== settings.transcriptionEngine).map(provider => <option key={provider} disabled={local && provider !== 'whisper'} value={provider}>{labels[provider]}</option>)}</select></label>
    </fieldset>
    <fieldset disabled={busy} className="space-y-4 border-t pt-4"><legend className="text-sm font-semibold">Text AI</legend>{(['analysis', 'document', 'chat'] as const).map(task => <div key={task} className="grid gap-3 sm:grid-cols-2">
      <label className="grid gap-2 text-sm">{task === 'analysis' ? 'Summaries' : task === 'document' ? 'Documents' : 'Chat'}<select className={selectClass} value={settings[`${task}Provider`]} onChange={e => update({ [`${task}Provider`]: e.target.value, [`${task}Model`]: '' })}>{text.map(provider => <option key={provider} value={provider} disabled={local && provider !== 'ollama'}>{labels[provider]}</option>)}</select></label>
      <label className="grid gap-2 text-sm">Model{settings[`${task}Provider`] === 'ollama' ? <select className={selectClass} value={settings[`${task}Model`]} onChange={e => update({ [`${task}Model`]: e.target.value })}><option value="">Select installed model</option>{models.map(model => <option key={model}>{model}</option>)}</select> : <Input value={settings[`${task}Model`]} placeholder="Provider default" onChange={e => update({ [`${task}Model`]: e.target.value })} />}</label>
    </div>)}{[settings.analysisProvider, settings.documentProvider, settings.chatProvider].includes('ollama') && <Button variant="outline" onClick={() => action(async () => setModels(await aiSettingsApi.models()))}><RefreshCw />Load local models</Button>}</fieldset>
    {used.length > 0 && <fieldset disabled={busy} className="space-y-4 border-t pt-4"><legend className="text-sm font-semibold">Credentials</legend>{used.map(provider => <div key={provider} className="flex items-end gap-2"><label className="grid flex-1 gap-2 text-sm">{labels[provider]} API key<Input type="password" autoComplete="off" value={keys[`${provider}ApiKey`] || ''} placeholder={settings.credentials[`${provider}ApiKey`] ? 'Saved key' : 'Not configured'} onChange={e => setKeys(value => ({ ...value, [`${provider}ApiKey`]: e.target.value }))} /></label><Button variant="outline" disabled={Object.keys(keys).length > 0} onClick={() => action(async () => { await aiSettingsApi.check(provider); setNotice(`${labels[provider]} connection verified`) })}>Check</Button></div>)}</fieldset>}
    <details className="border-t pt-4"><summary className="cursor-pointer text-sm">Processing jobs</summary><Button variant="ghost" className="my-2" onClick={() => action(async () => setJobs(await aiSettingsApi.jobs()))}><RefreshCw />Refresh</Button><ul className="divide-y">{jobs.slice().reverse().map(job => <li key={job.id} className="flex items-center gap-2 py-3 text-sm"><div className="min-w-0 flex-1"><p className="truncate">{labels[job.provider || ''] || 'Processing'} / {job.status}</p><p className="break-words text-xs text-muted-foreground">{job.error || job.checkpoint?.phase || job.recordingId}</p></div>{['running', 'pending'].includes(job.status) && <Button variant="ghost" size="icon" title="Cancel processing" onClick={() => action(async () => { await aiSettingsApi.cancel(job.id); setJobs(await aiSettingsApi.jobs()) })}><X /></Button>}{job.checkpoint?.remoteId && ['failed', 'cancelled'].includes(job.status) && <Button variant="outline" onClick={() => action(async () => { await aiSettingsApi.resume(job.id); setJobs(await aiSettingsApi.jobs()) })}>Resume</Button>}</li>)}</ul></details>
  </section>
}
